### ISSUE TITLE
Cannot Run Multiplet Detection Vignette

### ISSUE THREAD

**Issue by Yydtqqqg** [UcarLab/AMULET#14]
Hi! Thank you for developing this great tool!

I encountered this issue when trying to run the multiplet detection vignette:

> Filtering regions.
> Traceback (most recent call last):
  File "$PWD/AMULET-v1.1/AMULET.py", line 201, in <module>
    lengths = filtereddata[:,2]-filtereddata[:,1]+1
> IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

The number of valid read pairs seems good, but the number of overlaps are all zeros, and that's why I think it gives the above error.

`head -n 6 OverlapSummary.txt`

> Cell Id Number of Valid Read Pairs      Number of Overlaps      Barcode Total Number of Reads
10      9       0       TCACAGAGTACAACGG-1      278
100     95      0       GAACGTTAGAGTCCGA-1      620
101     195     0       TGTACGATCCTATCAT-1      1100
104     102     0       TCAGTCCAGGCTGGAT-1      496
105     208     0       TTGAGTGAGAAGCCTG-1      722

`cat Overlaps.txt`

> chr     start   end     cell id Min Overlap Count       Max Overlap Count       Mean Mapping Quality     Min Mapping Quality     Max Mapping Quality     Starts  Ends

`cat StatSummary.txt`

> Total Reads:    713014
Valid Read Pairs:       18305
Positive:       464525
Negative:       248489
Not in chromosome list: 15155
Insert size (<=0 or >900):      8
Low Mapping Quality Reads (<=30):       332222
Mean Read Length:       49.20841300191205
Mean Insert Size:       135.4882272603114
SAMTools Flag Checked:  188719
SAMTools Flag Passed:   187284
SAMTools Flag Duplicate:        1435
SAMTools Flag Unpaired: 0
SAMTools Flag Unmapped: 0
SAMTools Flag Mate Unmapped:    0
SAMTools Flag Secondary:        0
SAMTools Flag Reference Mismatch:       0

I followed the instructions on 10X genomics step by step and I don't know where I messed up. I checked my fastq files after running cellranger-atac mkfastq:
`(base) -bash-4.2$ ls -l HJN3KBCX2/outs/fastq_path/
总用量 424780
drwxr-xr-x 3 yuw044 ren-group         3 1月  30 12:28 p1
drwxr-xr-x 3 yuw044 ren-group         3 1月  30 12:28 Reports
drwxr-xr-x 2 yuw044 ren-group         8 1月  30 12:28 Stats
-rw-r--r-- 1 yuw044 ren-group  41185965 1月  30 12:28 Undetermined_S0_L001_I1_001.fastq.gz
-rw-r--r-- 1 yuw044 ren-group 156691442 1月  30 12:28 Undetermined_S0_L001_R1_001.fastq.gz
-rw-r--r-- 1 yuw044 ren-group  78766690 1月  30 12:28 Undetermined_S0_L001_R2_001.fastq.gz
-rw-r--r-- 1 yuw044 ren-group 157781371 1月  30 12:28 Undetermined_S0_L001_R3_001.fastq.gz`
`(base) -bash-4.2$ tree HJN3KBCX2/outs/fastq_path/p1/s1/
HJN3KBCX2/outs/fastq_path/p1/s1/
 test_sample_S1_L001_I1_001.fastq.gz
 test_sample_S1_L001_R1_001.fastq.gz
 test_sample_S1_L001_R2_001.fastq.gz
 test_sample_S1_L001_R3_001.fastq.gz
0 directories, 4 files`

I used the following options when running cellranger-atac count:
`--reference $pwd/opt/refdata-cellranger-arc-GRCh38-2020-A-2.0.0`
where I downloaded this reference file with this:
`wget https://cf.10xgenomics.com/supp/cell-atac/refdata-cellranger-arc-GRCh38-2020-A-2.0.0.tar.gz
`
`--fastqs` to the directory containing these files:
`(base) -bash-4.2$ tree HJN3KBCX2/outs/fastq_path/p1/s1/
HJN3KBCX2/outs/fastq_path/p1/s1/
 test_sample_S1_L001_I1_001.fastq.gz
 test_sample_S1_L001_R1_001.fastq.gz
 test_sample_S1_L001_R2_001.fastq.gz
 test_sample_S1_L001_R3_001.fastq.gz
0 directories, 4 files`

Can you help me with this problem?

**Comment by ajt986** [comment]
Hello! I think you're right that the problem is the number of overlaps are 0 for all the cells.  We will need to include a message indicating this is the case in the future to avoid confusion. I think this is related to the depth of the sample. Only  18305 valid read pairs found, so it's unlikely any overlaps are detected at all. It looks like half of the reads are not passing the mapping quality threshold: `Low Mapping Quality Reads (<=30): 332222`. You can try lowering this threshold using the `--mapqthresh` option.  Alternatively, I think it would be worthwhile to try running AMULET on the fragments.txt.gz output of CellRanger instead of the alignments (.bam).  With that said, it might be the case that the data is too sparse to detect any multiplets in the second step of AMULET. For comparison, `Valid Read Pairs:	124482084` is an example of one of the samples we tested AMULET on. I see that it says test_sample, have you tried with data with higher read depth?

**Comment by Yydtqqqg** [comment]
Thank you for the help! Actually I figured out my problem with the help of 10X Genomics. 

I downloaded the wrong dataset. The dataset I downloaded is a toy dataset found one [this page](https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/using/mkfastq). You can download real dataset from [this page](https://www.10xgenomics.com/resources/datasets?query=&page=1&configure%5Bfacets%5D%5B0%5D=chemistryVersionAndThroughput&configure%5Bfacets%5D%5B1%5D=pipeline.version&configure%5BhitsPerPage%5D=500). This should solve my problem.
