### ISSUE TITLE
how can i find known repetitive elements like restrictionlist_repeats_segdups_rmsk_hg19.bed ?

### ISSUE THREAD

**Issue by tianchen2019** [UcarLab/AMULET#15]
how can i find known repetitive elements like restrictionlist_repeats_segdups_rmsk_hg38.bed ? Can you provide the file or download link ?

**Comment by ajt986** [comment]
Hello, this file is merged from three sets of regions: simpleRepeats and genomicSuperDups from UCSC ( http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/ ) and the exclusion list from ENCODE ( https://www.encodeproject.org/files/ENCFF356LFX/ for GRCh38 or https://www.encodeproject.org/files/ENCFF001TDO/ for hg19 ).

**Comment by katimbach** [comment]
Hi,
 
Can you describe in a bit more detail how this step was done so we can sufficiently replicate the analysis? In my case, I am analyzing scATAC from the mm10 genome, so while I was able to find the corresponding annotations for that genome, it's not clear how to consolidate the regions into a clean bed for the analysis. Thanks!

**Comment by ajt986** [comment]
I used the getUnionPeaks function in peakoverlap.py (https://github.com/UcarLab/AMULET/blob/main/peakoverlap.py). Briefly, a union of the peaks is established by merging all locations that overlap by at least 1 bp. 

A more detailed list of these steps are as follows:

1) Location/peaks are concatenated into a single list.
2) Locations are separated by chromosome, and sorted by start position
3) For each chromosome, the sorted locations are examined, comparing the current location with the next location using the following conditions:

**If the current location is overlapping (at least 1bp):** the location end position is updated to be the maximum of the current location and the next location. 

**If the next location is not overlapping:** then the current location (using the updated end position) is added to the final list of locations and the next location becomes the new current location to compare against.

**Comment by katimbach** [comment]
Thank you for this insight!

However, I am still having a bit of trouble with the generation of the repeat BED file. I downloaded the same files as you mentioned earlier, but for mm10 as I am working with. For example, the files from UCSC have no header, so it's not entirely clear to me which I need to retain from each file to make them comparable. For example, https://hgdownload.soe.ucsc.edu/goldenPath/mm10/database/genomicSuperDups.txt.gz has multiple columns with chromosome annotation (first row has chr1 in column 2 and chr 5 in column 5). 

Is there any way you can provide more detail about how the data was processed before running the getUnionPeaks function? For example, convertToBEDFormatFromPosition generated the following error when I tried to run it on the genomicSuperDups data directly:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [35], in <cell line: 1>()
----> 1 convertToBEDFormatFromPosition(gsd)

Input In [32], in convertToBEDFormatFromPosition(data, startidx)
      2 """Converts position format positions to BED format.
      3     
      4     Parameters
   (...)
     16     position by one.
     17     """
     18 beddata = np.copy(data)
---> 19 beddata[:,startidx] = beddata[:,startidx]-1
     20 return beddata

TypeError: unsupported operand type(s) for -: 'str' and 'int'

```
Insight would be much appreciated, as a BED file for mm10 repeats doesn't seem readily available so I will need to generate it from scratch. Thank you!

**Comment by katimbach** [comment]
Also, here is a preview of the mm10 genomicSuperDups.txt file so you can see what I mean (read with pandas, though I did convert to a np array prior to running convertToBEDFormatFromPosition): 

  | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | ... | 20 | 21 | 22 | 23 | 24 | 25 | 26 | 27 | 28 | 29
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
611 | chr1 | 3531709 | 3535022 | chr5:133839256 | 0 | - | chr5 | 133839256 | 133842605 | ... | 80 | 3291 | 3070 | 221 | 121 | 100 | 0.932847 | 0.927492 | 0.070352 | 0.070537
626 | chr1 | 5423434 | 5429545 | chr10:55653424 | 0 | + | chr10 | 55653424 | 55659587 | ... | 60 | 6107 | 5873 | 234 | 136 | 98 | 0.961683 | 0.960425 | 0.039330 | 0.039405
626 | chr1 | 5423434 | 5429532 | chrX:108566838 | 0 | + | chrX | 108566838 | 108572997 | ... | 61 | 6098 | 5894 | 204 | 124 | 80 | 0.966546 | 0.965122 | 0.034223 | 0.034292
626 | chr1 | 5423435 | 5429437 | chr5:7766445 | 0 | + | chr5 | 7766445 | 7772518 | ... | 77 | 5999 | 5732 | 267 | 149 | 118 | 0.955493 | 0.953744 | 0.045883 | 0.045967
626 | chr1 | 5423435 | 5429545 | chr4:97080152 | 0 | + | chr4 | 97080152 | 97086317 | ... | 69 | 6103 | 5877 | 226 | 141 | 85 | 0.962969 | 0.961551 | 0.037976 | 0.038072
... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ...
586 | chrY_JH584303_random | 134412 | 147948 | chrY:9972352 | 0 | + | chrY | 9972352 | 9986281 | ... | 805 | 13330 | 13013 | 317 | 155 | 162 | 0.976219 | 0.973517 | 0.024166 | 0.024177
586 | chrY_JH584303_random | 136765 | 158098 | chrY:73175668 | 0 | + | chrY | 73175668 | 73196984 | ... | 163 | 21243 | 21043 | 200 | 94 | 106 | 0.990585 | 0.989235 | 0.009474 | 0.009476
586 | chrY_JH584303_random | 138511 | 158098 | chrY:79004141 | 0 | + | chrY | 79004141 | 79023814 | ... | 218 | 19521 | 19361 | 160 | 74 | 86 | 0.991804 | 0.990029 | 0.008241 | 0.008242
586 | chrY_JH584303_random | 141219 | 151072 | chrY:4328087 | 0 | + | chrY | 4328087 | 4337773 | ... | 607 | 9466 | 8974 | 492 | 211 | 281 | 0.948025 | 0.942845 | 0.053864 | 0.053886
586 | chrY_JH584303_random | 149451 | 158098 | chrY:88751824 | 0 | + | chrY | 88751824 | 88760415 | ... | 78 | 8580 | 8489 | 91 | 37 | 54 | 0.989394 | 0.988127 | 0.010682 | 0.010682

**Comment by ajt986** [comment]
More information on this table can be found here: http://genome.ucsc.edu/cgi-bin/hgTables?hgta_doSchemaDb=mm10&hgta_doSchemaTable=genomicSuperDups . 

I would extract all locations (columns 0,1,2 and 6,7,8 in the preview table above), listing them as their own positions in the bed-like files that will be merged.
