### ISSUE TITLE
Fragment files as input? 

### ISSUE THREAD

**Issue by caleblareau** [UcarLab/AMULET#5]
Hi Ucar Lab,

Thanks for the great tool--- have you all tried the statistical approach utilizing the [fragments.tsv.gz](https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/output/fragments) file as input instead of the .bam file? Do you have any sense off-hand on how it would perform? It'd greatly simplify my workflow as I have several fragments files but not .bam files saved from preprocessing runs.

**Comment by ajt986** [comment]
Just released a version that uses the fragment files. It's slightly different than using the bam files, but testing the current version using the the alignments versus the fragment files produced similar results.
