### ISSUE TITLE
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### ISSUE THREAD

**Issue by rylanci** [UcarLab/AMULET#7]
Hi there. I recently got this error when running the bash script . If I could get some help understanding the issue that would be great. Here is the traceback.

Traceback (most recent call last):
  File "/AMULET/AMULET.py", line 201, in <module>
    lengths = filtereddata[:,2]-filtereddata[:,1]+1
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

Thanks

**Comment by ajt986** [comment]
Hello,

This error suggests that after filtering there are 0 sites observing >2 reads, meaning the problem occurs further upstream from this error.  The OverlapSummary.txt output will tell you how many sites per cell/nucleus observe >2 reads. If many/all of these are 0 then this will result in this error since there are no sites to compare. Also check the number of valid reads, because if these counts are 0 it's possible that there's a chromosome id issue that can be resolved with an alternative list of chromosome ids.  

Alternatively, if there are sites with >2 reads being reported, then it's possible that the problematic/repetitive region filtering step is removing these, resulting in an empty array. 

Best,
Asa

**Comment by rylanci** [comment]
Okay thank you very much. In our case the OverlapSummary did not list any cells. The column headers are present but no additional rows. Sounds like this might closer to the root of the issue.

Interestingly the StatSummary recorded that it detected our reads, but we are unsure why valid read pairs and insert/read size fields are 0 or NA. 
```
Total Reads:    200381572
Valid Read Pairs:       0
Positive:       100190786
Negative:       100190786
Not in chromosome list: 0
Insert size (<=0 or >900):      0
Low Mapping Quality Reads (<=30):       565891
Mean Read Length:       NaN
Mean Insert Size:       NaN
SAMTools Flag Checked:  99907393
SAMTools Flag Passed:   53568106
SAMTools Flag Duplicate:        46339287
SAMTools Flag Unpaired: 0
SAMTools Flag Unmapped: 0
SAMTools Flag Mate Unmapped:    0
SAMTools Flag Secondary:        0
SAMTools Flag Reference Mismatch:       0
```

**Comment by ajt986** [comment]
It looks like the barcodes/cell ids are not being read properly. If the barcodes in the reads do not match those in the provided csv file, they are skipped. The singlecell.csv file should have barcodes that exactly match the ones used in the reads.  Two questions to ask to resolve this problem are:

1. What attribute is used to mark cell barcodes in these reads? For 10X/CellRanger-ATAC reads this should be CB.
2. What column information is in the csv file? Make sure that the column index (index obtained by counting columns, starting with 0 for the firstcolumn) designating the barcode is correct. Also make sure there is a column indicating whether the barcode corresponds to a cell and that this value is 1 to keep reads from this barcode. The cell id column must also be unique or multiple barcodes will be assigned as if they are for the same, but this can just be set to the same barcode column index.

More specifically you'll need to check these aspects of your input files and use these options:
`--bambc` The bam file attribute to use to extract the barcode from reads (Default: "CB")

`--bcidx` The column index (counting from 0) of the CSV file barcode to cell id map for the barcode. (Default: 0)

`--cellidx` The column index (counting from 0) of the CSV file barcode to cell id map for the cell id. (Default: 8)

`--iscellidx` The column index (counting from 0) of the CSV file barcode to cell id map for determining if the barcode corresponds to a cell. (Default: 9)

to inform AMULET of where to find the information it needs to bin reads to their respective cells.. Alternatively, a fragment file ( https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/output/fragments ) can be used as input as well if that is available.
