### ISSUE TITLE
Comment lines in fragments

### ISSUE THREAD

**Issue by Zepeng-Mu** [UcarLab/AMULET#8]
Hi, the fragment files from cellranger-atac 2.0.0 contains some comment lines starting with "#". I think currently this is not handled in AMULET, which throws an error. I added two lines of code myself that skips the comment lines and everything runs fine.

Thanks so much!

**Comment by ajt986** [comment]
Thank you for pointing this out! I've just added a few lines of code to skip these lines in the fragment file so that AMULET can run correctly with cell ranger ATAC 2.0 outputs.
